### ISSUE TITLE
[BUG] Difficulty spike with Iron Difficulty

### ISSUE THREAD

**Issue by Eonfge** [Quitch/GW-AI-Overhaul#51]
## Describe the bug

This is not really a technical bug (so I removed the previous fluff) but a design problem; I found that the difficulty ramp-up from Casual to Iron was too big.

## To Reproduce

Previously I played and won Galactic War on Casual: I don't camp much and a 1 vs 1 game against a Casual AI takes me around ~20 minutes. That said, they never posted more then a minor challenge to so started a second Galactic War on Iron... and I run into a brick wall.

Once I make it to one of the faction leaders, I'm suddenly in a 2 vs 1, where the AI expends in all directions, and I can't economically keep up: Or they win the space race and I die by death from above, or I keep control over the skies but I slowly and steadily loose ground control.

## Actions

I feel that a more gradual development might be necessary. I understand that I'm just a casual player and that most PA players will laugh at an Iron AI, but I do hope that early on, players can get some more slack.

## GW Details

- Version: 5.32.0
- Difficulty: Iron
- Size: Medium
- AI: Queller
- Options: Faction scaling, System scaling

- Bot commander
  - Complete Air
  - Complete Orbital
  - Artillery
  - Complete Energy
  - Titan Tech

**Comment by laodie666** [comment]
ok just saying queller ai is prob why u have so much issue. Difficulty for GW only influence the tech ai gets and what econ rate they have, but not their actual performance. The ai used for the enemy for queller ai is queller uber, meaning the ai will play very well even if they have econ penalty in iron, especially considering u are a new player. This is why I suggest u to use penchant ai or titan ai. 

Would be rlly nice if the enemy's skill level can be customized tho rather than only being able to tweak their econ rate.

**Comment by Quitch** [comment]
You're using the Queller AI, which is described as " greater challenge at the cost of performance". You should use TITANS or Penchant if you are finding things too hard.
